name: world_liturgy_app
description: The framework for all World Liturgy Apps
version: 2.0.0


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: '>=0.1.0'

  xml: '^3.0.0'

  #library to convert the xml files to json
  xml2json: '>=4.2.0'

  #to transform the JSON into Dart object
  #works with build_runner and json_serializable
  json_annotation: '>=3.0.1'

  #add function to capitalize
  strings: '>=0.1.2'

#currently needing resolution of https://github.com/flutter/flutter/issues/12319

# for finding paths -- e.g. where to store SQL database
  path_provider: ">=1.6.7"

#  good looking calendar
  flutter_calendar: '>=0.0.9'

# storing user preferences on both android and iOs
  shared_preferences: '>=0.5.7'

#  build: '^1.2.2'
#  path: '^1.7.0'

dev_dependencies:
  #works with json_annotation. see above
  build_runner: '>=1.9.0'
  json_serializable: '>=3.3.0'

#  build_config: '^0.4.2'

#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/wlp_format/docs/prayerBooks.xml
    - assets/wlp_format/docs/prayerBooksSample.xml
    - assets/wlp_format/docs/calendar.xml
    - assets/wlp_format/docs/calendarSample.xml
    - assets/wlp_format/docs/songBooksSample.xml
    - assets/wlp_format/docs/tenziZaRohoni.xml

    - assets/bibles/WEB/metadata.xml
    - assets/bibles/WEB/release/versification.vrs
    - assets/bibles/WEB/release/USX_4/

    - assets/bibles/SUV.xml
    - assets/bibles/SWA.xml

#    - assets/songBooks/english_songs/index.json
    - assets/songBooks/english_songs/songs/


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
#        - asset: assets/fonts/WorkSans-Thin.ttf
#          weight: 100
#        - asset: assets/fonts/WorkSans-ExtraLight.ttf
#          weight: 200
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
#        - asset: assets/fonts/WorkSans-Medium.ttf
#          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
#        - asset: assets/fonts/WorkSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/WorkSans-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/WorkSans-Black.ttf
#          weight: 900
    - family: Signika
      fonts:
#        - asset: assets/fonts/Signika-Regular.ttf
#        - asset: assets/fonts/Signika-Light.ttf
#          weight: 200
        - asset: assets/fonts/Signika-SemiBold.ttf
          weight: 600
#        - asset: assets/fonts/Signika-Bold.ttf
#          weight: 800

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages